config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "pages#home"
  resources :messages

  resources :finances
  resources :gratitudes
  resources :meals
  resources :notes
  resources :self_cares
  resources :users
  resources :completed_cares
  resources :goals do
    patch :complete
  end
  
  resources :pages do
    resources :finances
    resources :gratitudes
    resources :meals
    resources :notes
    resources :goals do
      patch :complete
    end
  end

  get "daily", to: "pages#daily"
  get "monthly", to: "pages#monthly"
  get 'up_daily', to: 'sessions#up_daily'
  get 'down_daily', to: 'sessions#down_daily'
  get 'reset_daily', to: 'sessions#reset_daily'
  get 'up_monthly', to: 'sessions#up_monthly'
  get 'down_monthly', to: 'sessions#down_monthly'
  get 'reset_monthly', to: 'sessions#reset_monthly'
  get 'dark', to: 'application#dark'
  get 'light', to: 'application#light'
  get 'tracker_menu', to: 'pages#tracker_menu'
  get "account", to: "pages#account"
  patch 'confirm_invite', to: 'invitations#update'
  get "add_friend", to: "invitations#new"
  post "add_friend", to: "invitations#create"
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create'
  match 'auth/failure', to: redirect('/login'), via: [:get, :post]
  get 'password', to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'
end

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :user

    validates :content, presence: true
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    
    def show
        @note = current_user.notes.find(params[:id])
    end

    def new
        @note = current_user.notes.new(date: Date.today)
    end

    def create
        @note = current_user.notes.new(note_params)
        if @note.save
            redirect_to session[:return]
        else
            render :new
        end
    end

    def edit
        @note = current_user.notes.find(params[:id])
    end

    def update
        @note = current_user.notes.find(params[:id])
        @note.update(note_params)
        
        redirect_to session[:return]
    end

    def destroy
        @note = current_user.notes.find(params[:id])
        @note.destroy
        redirect_to session[:return]
    end

    private

    def note_params
        params.require(:note)
        .permit(:user_id, :content, :date)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_error.html.erb
<% if !@note.errors.empty? %>
  <ul class="errors">
    <% @note.errors.full_messages.each do |error| %>
      <li class="row space-between task-bubble red">
        <%= error %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/notes/_form.html.erb
<%= form_with model: @note do |f| %>
  <hr>
  <div>
    <%= f.text_area :content, placeholder: "Content" %>
  </div>
        
  <div class="row space-between">
    <%= f.date_field :date %>

    <%= f.submit 'Save', class: "button" %>
  </div>
<% end %>

app/views/notes/_list_notes.html.erb
<% if notes %>
    <ul>
        <% notes.each do |note| %>
            <li class="row space-between super-light task-bubble dark">
                <h5><%= link_to note[:content], note_path(note) %></h5>
            </li>
        <% end %>
    </ul>
<% end %>

app/views/notes/_quick_note.html.erb
<%= form_for :note, url: notes_path do |f| %>
    <%= f.hidden_field :date, value: Date.today %>

    <div class="row emoji-form">
        <%= f.text_field :content, placeholder: "Note" %>

        <%= f.submit '🏹' %>
    </div>
<% end %>

app/views/notes/edit.html.erb
<div class="full-height vertically-center">
    <%= render 'error' %>

    <div class="container mid">
        <h2>Edit Note</h2>
        <%= render 'form' %>
    </div>
</div>

app/views/notes/new.html.erb
<div class="full-height vertically-center">
    <%= render 'error' %>

    <div class="container mid">
        <h2>New Note</h2>
        <%= render 'form' %>
    </div>
</div>

app/views/notes/show.html.erb
<div class="full-height vertically-center">
    <%= render 'error' %>

    <div class="container mid">
        <div class="row">
            <h2>Note</h2>
            <%= link_to '✏️', edit_note_path %>
            <%= link_to '❌', note_path(@note), method: :delete %>
        </div>
        <hr>
        <p><%= @note.content %></p>
    </div>
</div>