config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "pages#home"
  resources :messages

  resources :finances
  resources :gratitudes
  resources :meals
  resources :notes
  resources :self_cares
  resources :users
  resources :completed_cares
  resources :goals do
    patch :complete
  end
  
  resources :pages do
    resources :finances
    resources :gratitudes
    resources :meals
    resources :notes
    resources :goals do
      patch :complete
    end
  end

  get "daily", to: "pages#daily"
  get "monthly", to: "pages#monthly"
  get 'up_daily', to: 'sessions#up_daily'
  get 'down_daily', to: 'sessions#down_daily'
  get 'reset_daily', to: 'sessions#reset_daily'
  get 'up_monthly', to: 'sessions#up_monthly'
  get 'down_monthly', to: 'sessions#down_monthly'
  get 'reset_monthly', to: 'sessions#reset_monthly'
  get 'dark', to: 'application#dark'
  get 'light', to: 'application#light'
  get 'tracker_menu', to: 'pages#tracker_menu'
  get "account", to: "pages#account"
  patch 'confirm_invite', to: 'invitations#update'
  get "add_friend", to: "invitations#new"
  post "add_friend", to: "invitations#create"
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create'
  match 'auth/failure', to: redirect('/login'), via: [:get, :post]
  get 'password', to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'
end

app/models/meal.rb
class Meal < ApplicationRecord
    belongs_to :user
    belongs_to :food

    scope :meals, -> (type) { where(meal_type: type) }
    
    def food_attributes=(food)
        self.food = Food.find_by(name: food[:name]) || Food.create(food)
    end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

    def index
        @meals = current_user.meals
    end
    
    def show
        @meal = current_user.meals.find(params[:id])
    end

    def new
        @meal = current_user.meals.new(date: Date.today)
        @meal.food = @meal.build_food
    end

    def create
        @meal = current_user.meals.new(meal_params)
        if @meal.save
            redirect_to session[:return]
        else
            render :new
        end
    end

    private

    def meal_params
        params.require(:meal)
        .permit(
            :date, :meal_type, food_attributes: [
                :name, :user_id
            ]
        ).with_defaults(user_id: session[:user_id])
    end
end

app/helpers/meals_helper.rb
module MealsHelper
    def meal_type_options
        [
            ['Breakfast', 'breakfast'],
            ['Lunch', 'lunch'],
            ['Dinner', 'dinner'],
            ['Snack', 'snack']
        ]
    end
end

app/views/meals/_food_list.html.erb
<% if meals.count >= 1 %>
    <ul>
        <% meals[0..-2].each do |meal| %>
            <li class="row space-between super-light task-bubble dark">
                <h5 class="left"><%=  meal.food.name %></h5>
            </li>
        <% end %>
        <li class="row space-between super-light task-bubble dark">
            <h5><%= meals[-1].food.name %></h5>
            <%= link_to '➕', new_meal_path(meals[-1]) %>
        </li>
    </ul>
<% else %>
    <%= form_for :meal, url: meals_path do |f| %>
        <%= f.hidden_field :date, value: Date.today %>
        <%= f.hidden_field :meal_type, value: meal_type %>

        <div class="row emoji-form">
            <%= f.fields_for :food_attributes do |ff| %>
                <%= ff.hidden_field :user_id, value: current_user.id %>
                <%= ff.text_field :name, placeholder: meal_type %>
            <% end %>

            <%= f.submit '🏹' %>
        </div>
    <% end %>
<% end %>

app/views/meals/_meal_tracker.html.erb
<div class="container column-container mid">
    <div class="row">
        <h2><%= link_to 'Breakfast', meals_path %></h2><hr>
    </div>
    <%= render 'meals/food_list', {meals: breakfast, meal_type: "breakfast"} %>
    <div class="row">
        <h2>Lunch</h2><hr>
    </div>
    <%= render 'meals/food_list', {meals: lunch, meal_type: "lunch"} %>
    <div class="row">
        <h2>Dinner</h2><hr>
    </div>
    <%= render 'meals/food_list', {meals: dinner, meal_type: "dinner"} %>
    <div class="row">
        <h2>Snack</h2><hr>
    </div>
    <%= render 'meals/food_list', {meals: snack, meal_type: "snack"} %>
</div>

app/views/meals/index.html.erb
<%= @meals.each do |meal| %>
    <h1><%= meal.meal %><%= meal.food.name if meal.food %></h1>
<% end %>

app/views/meals/new.html.erb
<div class="full-height vertically-center">
  <% if !@meal.errors.empty? %>
    <ul class="errors">
      <% @meal.errors.full_messages.each do |error| %>
        <li class="row space-between task-bubble red">
          <%= error %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <div class="container mid">
    <h2>New Meal</h2>
    <hr class="rounded">
    <%= form_for @meal do |f| %>
      <div class="row">
        <%= f.fields_for :food_attributes do |ff| %>
          <%= ff.hidden_field :user_id, value: current_user.id %>
          <%= ff.text_field :name, placeholder: "Food", class: "food-list" %>
        <% end %>
        <%= f.select :meal_type, meal_type_options, {}, prompt: 'Select One' %>
      </div>
      <div class="row">
        <%= f.date_field :date %>

        <%= f.submit 'Save', class: "button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/meals/show.html.erb
<div class="full-height vertically-center">
    <div class="container mid">
        <div class="row">
            <h2>Meal</h2>
            <%= link_to '✏️', edit_meal_path %>
            <%= link_to '❌', meal_path(@meal), method: :delete %>
        </div>
        <hr>
        <div class="super-light task-bubble">
            <h5><%= @meal.name %></h5>
        </div>
    </div>
</div>