config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "pages#home"
  resources :messages

  resources :finances
  resources :gratitudes
  resources :meals
  resources :notes
  resources :self_cares
  resources :users
  resources :completed_cares
  resources :goals do
    patch :complete
  end
  
  resources :pages do
    resources :finances
    resources :gratitudes
    resources :meals
    resources :notes
    resources :goals do
      patch :complete
    end
  end

  get "daily", to: "pages#daily"
  get "monthly", to: "pages#monthly"
  get 'up_daily', to: 'sessions#up_daily'
  get 'down_daily', to: 'sessions#down_daily'
  get 'reset_daily', to: 'sessions#reset_daily'
  get 'up_monthly', to: 'sessions#up_monthly'
  get 'down_monthly', to: 'sessions#down_monthly'
  get 'reset_monthly', to: 'sessions#reset_monthly'
  get 'dark', to: 'application#dark'
  get 'light', to: 'application#light'
  get 'tracker_menu', to: 'pages#tracker_menu'
  get "account", to: "pages#account"
  patch 'confirm_invite', to: 'invitations#update'
  get "add_friend", to: "invitations#new"
  post "add_friend", to: "invitations#create"
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create'
  match 'auth/failure', to: redirect('/login'), via: [:get, :post]
  get 'password', to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'
end

app/models/goal.rb
class Goal < ApplicationRecord
    has_many :users

    validates :goal, presence: true, length: { maximum: 30}

    scope :not_priority, -> { where(priority: false) }

    scope :priority, -> { where(priority: true) }
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
    before_action :set_goal, except: [:new, :create, :complete]
    
    def show
    end

    def new
        @goal = current_user.goals.new(date: Date.today)
    end

    def create
        @goal = current_user.goals.new(goal_params)
        if @goal.save
            redirect_to session[:return]
        else
            render :new
        end
    end

    def edit
    end

    def update
        @goal.update(goal_params)
        
        redirect_to session[:return]
    end

    def destroy
        @goal.destroy
        redirect_to session[:return]
    end

    def complete
        @goal = current_user.goals.find(params[:goal_id])
        @goal.update_attribute(:completed, !@goal[:completed])
        redirect_to session[:return]
    end

    private

    def set_goal
        @goal = current_user.goals.find(params[:id])
    end

    def goal_params
        params.require(:goal)
        .permit(:goal, :priority, :user_id, :more_info, :date, :completed)
        .with_defaults(priority: false, date: Date.today, completed: false)
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_completed.html.erb
<% if goal.completed %>
    <h5><s><%= link_to goal[:goal], goal_complete_path(goal), method: :patch %></s></h5>
<% else %>
    <h5><%= link_to goal[:goal], goal_complete_path(goal), method: :patch %></h5>
<% end %>

app/views/goals/_error.html.erb
<% if !@goal.errors.empty? %>
  <ul class="errors">
    <% @goal.errors.full_messages.each do |error| %>
      <li class="row space-between task-bubble red">
        <%= error %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/goals/_form.html.erb
<%= form_for @goal do |f| %>
  <div class="row">
    <%= f.text_field :goal, placeholder: "Goal" %>

    
    <%= f.date_field :date %>
  </div>

  <div>
    <%= f.text_area :more_info, placeholder: "More Info" %>
  </div>
        
  <div class="row space-between">
    <label class="checkmark-container">High Priority
      <%= f.check_box :priority %>
      <span class="checkmark"></span>
    </label>

    <%= f.submit 'Save', class: "button" %>
  </div>
<% end %>

app/views/goals/_list_goals.html.erb
<% if goals %>
    <ul>
        <% goals.each do |goal| %>
            <li class="row space-between super-light task-bubble dark">
                <%= render 'goals/completed', {goal: goal} %>
                <%= link_to '💌', goal_path(goal) %>
            </li>
        <% end %>
    </ul>
<% end %>

app/views/goals/_quick_form.html.erb
<%= form_for :goal, url: goals_path do |f| %>
    <%= f.hidden_field :priority, value: priority %>
    
    <% if show_date %>
        <%= f.text_field :goal, placeholder: "#{priority ? "Priority" : "Goal"}" %>
        <div class="row space-between">
            <%= f.date_field :date, value: date %>
            <%= f.submit 'Save', class: "button" %>
        </div>
    <% else %>
        <%= f.hidden_field :date, value: date %>
        <div class="row emoji-form">
            <%= f.text_field :goal, placeholder: "#{priority ? "Priority" : "Goal"}" %>
            <%= f.submit '🏹' %>
        </div>
    <% end %>
<% end %>

app/views/goals/edit.html.erb
<div class="full-height vertically-center">
    <%= render 'error' %>

    <div class="container mid">
        <h2>Edit Goal</h2>
        <hr class="rounded">
        <%= render 'form' %>
    </div>
</div>

app/views/goals/new.html.erb
<div class="full-height vertically-center">
    <%= render 'error' %>

    <div class="container mid">
        <h2>New Goal</h2>
        <hr class="rounded">
        <%= render 'form' %>
    </div>
</div>

app/views/goals/show.html.erb
<div class="full-height vertically-center">
    <%= render 'error' %>

    <div class="container mid">
        <div class="row">
            <h2><%= @goal.goal %></h2>
            <%= link_to '✏️', edit_goal_path %>
            <%= link_to '❌', goal_path(@goal), method: :delete %>
        </div>
        <hr>
        <% if @goal.more_info %>
            <div class="super-light task-bubble">
                <h5><%= @goal.more_info %></h5>
            </div>
        <% end %>
        <div class="row space-between">
            <div class="super-light task-bubble">
                <h5><%= @goal.date %></h5>
            </div>
            <div class="super-light task-bubble">
                <h5><%= @goal.priority ? "High Priority" : "Low Priority" %></h5>
            </div>
        </div>
    </div>
</div>