config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "pages#home"
  resources :messages

  resources :finances
  resources :gratitudes
  resources :meals
  resources :notes
  resources :self_cares
  resources :users
  resources :completed_cares
  resources :goals do
    patch :complete
  end
  
  resources :pages do
    resources :finances
    resources :gratitudes
    resources :meals
    resources :notes
    resources :goals do
      patch :complete
    end
  end

  get "daily", to: "pages#daily"
  get "monthly", to: "pages#monthly"
  get 'up_daily', to: 'sessions#up_daily'
  get 'down_daily', to: 'sessions#down_daily'
  get 'reset_daily', to: 'sessions#reset_daily'
  get 'up_monthly', to: 'sessions#up_monthly'
  get 'down_monthly', to: 'sessions#down_monthly'
  get 'reset_monthly', to: 'sessions#reset_monthly'
  get 'dark', to: 'application#dark'
  get 'light', to: 'application#light'
  get 'tracker_menu', to: 'pages#tracker_menu'
  get "account", to: "pages#account"
  patch 'confirm_invite', to: 'invitations#update'
  get "add_friend", to: "invitations#new"
  post "add_friend", to: "invitations#create"
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create'
  match 'auth/failure', to: redirect('/login'), via: [:get, :post]
  get 'password', to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/finance.rb
class Finance < ApplicationRecord
    belongs_to :user

    validates :amount, presence: true
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :meals
  has_many :users, through: :meals

  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 50}
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/goal.rb
class Goal < ApplicationRecord
    has_many :users

    validates :goal, presence: true, length: { maximum: 30}

    scope :not_priority, -> { where(priority: false) }

    scope :priority, -> { where(priority: true) }
end

app/models/gratitude.rb
class Gratitude < ApplicationRecord
    belongs_to :user

    validates :name, presence: true, length: { maximum: 20}

    scope :today, -> { where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User", foreign_key: :friend_id
  scope :pending_requests, -> {where(confirmed: false)}
  scope :confirmed_requests, -> { where(confirmed: true)}
  scope :incoming_invitations, -> (user) {where(friend_id: user)}
  scope :outgoing_invitations, -> (user) {where(user_id: user)}
end

app/models/meal.rb
class Meal < ApplicationRecord
    belongs_to :user
    belongs_to :food

    scope :meals, -> (type) { where(meal_type: type) }
    
    def food_attributes=(food)
        self.food = Food.find_by(name: food[:name]) || Food.create(food)
    end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User", foreign_key: :friend_id

  scope :outgoing_messages, -> (user) {where(user_id: user)}
  scope :incoming_messages, -> (user) {where(friend_id: user)}
end

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :user

    validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    mount_uploader :image, ImageUploader

    has_secure_password
    validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 5}
    validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }

    has_many :finances
    has_many :meals
    has_many :goals
    has_many :gratitudes
    has_many :notes
    has_many :self_cares
    has_many :completed_cares
    has_many :foods
    has_many :foods_eaten, through: :meals
    has_many :invitations
    has_many :messages
    has_many :accepted_invitations, -> { where(confirmed: true) }, class_name: "Invitation"
    has_many :friends_added, through: :accepted_invitations, source: :friend 
    has_many :added_friends, through: :accepted_invitations, source: :user 

    def self.find_or_create_by_omniauth(auth)
      oauth_email = auth["info"]["email"] || auth["info"]["nickname"] || auth["info"]["name"]
      self.where(:email => oauth_email).first_or_create do |user|
        user.password = SecureRandom.hex
      end
    end
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/finances_helper.rb
module FinancesHelper
    def options_for_status
        [
            ['Incoming', 'incoming'],
            ['Outgoing', 'outgoing']
        ]
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/gratitudes_helper.rb
module GratitudesHelper
end

app/helpers/meals_helper.rb
module MealsHelper
    def meal_type_options
        [
            ['Breakfast', 'breakfast'],
            ['Lunch', 'lunch'],
            ['Dinner', 'dinner'],
            ['Snack', 'snack']
        ]
    end
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
    def current_date
        daily_date.strftime("%A, #{daily_date.day.ordinalize} of %B")
    end

    def current_month
        monthly_date.strftime("%B")
    end

    def goals
        current_user.goals.today(daily_date).not_priority.to_a
    end

    def priorities
        current_user.goals.today(daily_date).priority.to_a
    end

    def tomorrows_goals
        current_user.goals.tomorrow(daily_date).to_a
    end

    def monthly_goals
        current_user.goals.monthly(monthly_date).not_priority.to_a
    end

    def monthly_priorities
        current_user.goals.monthly(monthly_date).priority.to_a
    end

    def finance_progress
        if monthly_earnings != 0 && monthly_expenses != 0
            percentage = (monthly_expenses.to_f/monthly_earnings.to_f)*100.0
            percentage.to_i
        end
    end

    def self_care_progress goal, completed
        percentage = (completed.to_f/goal.to_f)*100.0
        percentage.to_i
    end

    def self_cares
        current_user.self_cares.to_a
    end

    def completed_cares self_care_id
        CompletedCare.where("self_cares_id = ?", self_care_id).to_a.last
    end

    # MEALS

    def breakfast
        breakfast = current_user.meals.today(daily_date).meals("breakfast").to_a
    end

    def lunch
        current_user.meals.today(daily_date).meals("lunch").to_a
    end

    def dinner
        current_user.meals.today(daily_date).meals("dinner").to_a
    end

    def snack
        current_user.meals.today(daily_date).meals("snack").to_a
    end

    # NOTES

    def notes
        current_user.notes.today(daily_date).to_a
    end

    def monthly_notes
        current_user.notes.monthly(monthly_date).to_a
    end

    # GRATITUDES

    def gratitudes
        current_user.gratitudes.today.to_a
    end

    def monthly_gratitudes
        current_user.gratitudes.datetime_monthly(monthly_datetime).to_a
    end

    # ACCOUNT

    def incoming_invites
        Invitation.incoming_invitations(session[:user_id]).pending_requests
    end

    def outgoing_invites
        Invitation.outgoing_invitations(session[:user_id]).pending_requests
    end

    def incoming_confirmed
        Invitation.incoming_invitations(session[:user_id]).confirmed_requests
    end

    def outgoing_confirmed
        Invitation.outgoing_invitations(session[:user_id]).confirmed_requests
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_head.html.erb
  <head>
    <title>DreamJournal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% if cookies[:dark] %>
      <%= stylesheet_link_tag 'dark', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% else %>
      <%= stylesheet_link_tag 'light', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% end %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', :defer => "defer" %>
  </head>

app/views/layouts/_menu.html.erb
<header id="menu">
    <div id="menu-icons">
        <button class="toggle_menu">📁</button>
        <%= link_to "🏠", root_path if !Current.user %>
        <% if Current.user %>
            <%= link_to "📆", reset_daily_path %>
            <%= link_to "📅", reset_monthly_path %>
            <%= link_to "👤", account_path %>
            <button class="toggle_tracker_menu">➕</button>
        <% end %>
    </div>
    <nav class="hide" id="nav-dropdown">
      <span>
        <button class="close-menu toggle_menu">❌</button>
      </span>
      <ul>
        <li>
          <h2><%= link_to "Dream Journal", root_path %></h2>
        </li>
        <hr class="rounded">
        <% if Current.user %>
          <li><%= link_to "Daily", reset_daily_path %></li>
          <li><%= link_to "Monthly", reset_monthly_path %></li>
          <li><%= link_to "Account", account_path %></li>
          <li class="row">
            <%= button_to 'Sign Out', sign_out_path, method: :delete, class: 'button mid' %>
          </li>
        <% else %>
          <li><%= link_to 'Sign In', login_path, class: 'button mid' %></li>
        <% end %>
      </ul>
    </nav>

    <nav class="hide" id="tracker-dropdown">
      <span>
        <button class="close-menu toggle_tracker_menu">❌</button>
      </span>
      <ul>
          <li><%= link_to 'Goals', new_goal_path %></li>
          <li><%= link_to 'Meals', new_meal_path %></li>
          <li><%= link_to 'Finances', new_finance_path %></li>
          <li><%= link_to 'Notes', new_note_path %></li>
          <li><%= link_to 'Gratitude', new_gratitude_path %></li>
      </ul>
    </nav>
</header>

<%= javascript_pack_tag 'toggleMenu' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>

  <body>
    <%= render 'layouts/menu' %>
    <%= yield %>
  </body><div id="fb-root"></div>
</html>

app/views/pages/_lists.html.erb
<div class="container mid">
    <% if list.blank? %>
        <% list.each do |goal| %>
            <div>
                <%= link_to goal.name, edit_goal_path(goal) %>
            </div>
        <% end %>
    <% end %>
    <%= link_to "Add Goal", new_goal_path, class: "button light" %>
</div>

app/views/pages/account.html.erb
<% if cookies[:dark] %>
    <%= button_to 'Light Mode', light_path, method: :get, class: "rotate-header colour-mode" %>
<% else %>
    <%= button_to 'Dark Mode', dark_path, method: :get, class: "rotate-header colour-mode" %>
<% end %>

<div class="full-height vertically-center">
    <div class="container account-column mid">
        <%= render 'users/avatar', { user: @user, size: 'avatar' } %>
        <li class="super-light task-bubble">
            <%= @user.username %>
        </li>
        <div class="row">
            <%= link_to "Update Account",
            edit_user_path(@user),
            class: "button light" %>

            <%= link_to "Delete Account",
            user_path(@user),
            method: :delete,
            data: { confirm: 'Are you sure you want to delete this account permanently?' },
            class: "button light" %>
        </div>
    </div>

    <hr class="hr-column">

    <div class="container account-column mid friends-list">
        <h2>Friends</h2>
        <ul>
            <%= render 'invitations/pending', {invites: incoming_invites, type: 'incoming'} %>
            <%= render 'invitations/pending', {invites: outgoing_invites, type: 'outgoing'} %>
            <% if incoming_confirmed.count != 0 ||  outgoing_confirmed.count != 0 %>
                <%= render 'invitations/confirmed', {invites: incoming_confirmed, type: 'incoming'} %>
                <%= render 'invitations/confirmed', {invites: outgoing_confirmed, type: 'outgoing'} %>
            <% else %>
                <li>You have no friends.</li>
            <% end %>
        </ul>
        <%= link_to "Add Friend", add_friend_path, class: "button light" %>
    </div>
</div>

app/views/pages/daily.html.erb
<h3 class="rotate-header"><%= link_to '↤', down_daily_path %> <%= current_date %> <%= link_to '↦', up_daily_path %></h3>

<div class="row red columns">
    <div class="column">
        <div class="container mid header-bubble">
            <h2>Top Priorities</h2>
        </div>
        <div class="container column-container light-mid">
            <%= render "goals/list_goals", { goals: priorities} %> 
            <%= render 'goals/quick_form', {priority: true, show_date: false, date: daily_date} %>
        </div>

        <div class="container mid header-bubble">
            <h2>Todays Goals</h2>
        </div>
        <div class="container column-container light-mid">
            <%= render "goals/list_goals", { goals: goals} %> 
            <%= render 'goals/quick_form', {priority: false, show_date: false, date: daily_date} %>
        </div>

        <div class="container column-container light-mid">
            <h2 class="mini-header">Coming Up...</h2>
            <%= render "goals/list_goals", { goals: tomorrows_goals} %> 
            <%= render 'goals/quick_form', {priority: false, show_date: true, date: tomorrows_date} %>
        </div>
    </div>

    <div class="column">
        <div class="container column-container light-mid">
            <h2 class="mini-header">I'm Grateful For</h2>
            <%= render 'gratitudes/list_new' %>
        </div>


        <%= render "meals/meal_tracker" %>
    </div>

    <div class="column">
        <%= render "finances/daily_tracker" %>
        
        <div class="container mid header-bubble">
            <h2>Notes</h2>
        </div>
        <div class="container column-container light-mid">
            <%= render "notes/list_notes" %> 
            <%= render 'notes/quick_note' %>
        </div>
    </div>
</div>

<%= javascript_pack_tag "toggleMenu" %>

app/views/pages/home.html.erb
<div id="home">
    <div class="full-height full-width home-1">
        <h1>Get your sh*t together</h1>
        <%= link_to "Sign up now", login_path, class: 'button' %>

        <h4>Keep track of everything you want<br>and nothing you dont...</h4>
        <h4 class="fade">goals<br>meals<br>water<br>finances<br>gratitude<br>etc.</h4>
    </div>
    <div class="full-height full-width" id="home-2">
        <div class="big-column">
            <%= image_tag("monthly_window.png", :alt => "Monthly Tracker Window") %>
            <%= link_to "Get started today", login_path, class: 'button' %>
        </div>
        <div class="little-column">
            <h3 class="red">Your new best<br>friend to help<br>you get your<br>sh*t together...</h3>
            <%= image_tag("mobile_tracker_window.jpg", :alt => "Mobile Tracker") %>
        </div>
    </div>
</div>

app/views/pages/monthly.html.erb
<h3 class="rotate-header"><%= link_to '↤', down_monthly_path %> <%= current_month %> <%= link_to '↦', up_monthly_path %></h3>

<div class="row red columns">
    <div class="column">
        <div class="container column-container mid">
            <h2 class="mini-header">Priorities</h2>
            <%= render "goals/list_goals", { goals: monthly_priorities } %> 
            <%= render "goals/quick_form", {priority: true, show_date: true, date: monthly_date} %>
        </div>
        <div class="container column-container mid">
            <h2 class="mini-header">Goals</h2>
            <%= render "goals/list_goals", { goals: monthly_goals} %> 
            <%= render "goals/quick_form", {priority: false, show_date: true, date: monthly_date} %>
        </div>
    </div>
    <div class="column">
        <div class="container mid header-bubble">
            <h2>I'm Grateful For</h2>
        </div>
        <div class="container column-container light-mid">
            <%= render 'gratitudes/list_new', {gratitudes: monthly_gratitudes} %>
        </div>
        <%= render 'finances/progress' %>
    </div>
    <div class="column">
        <div class="container column-container mid">
            <h2 class="mini-header">Notes</h2>
            <%= render "notes/list_notes", {notes: monthly_notes} %> 
            <%= render 'notes/quick_note' %>
        </div>
    </div>
</div>